# Docs
# https://github.com/softprops/action-gh-release

name: Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Install tools
        run: |
          # sudo apt update
          sudo apt -y install make zip

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Create binaries
        if: startsWith(github.ref, 'refs/tags/')
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            fsync-darwin-amd64.zip
            fsync-darwin-arm64.zip
            fsync-linux-amd64.zip
            fsync-windows-amd64.zip
